#ifndef CONSTS_H
#define CONSTS_H

#define STATIC_TEST_ENTITY_COUNT 250000

#define RAMP_UP_TEST_ENTITY_COUNT_START 100000
#define RAMP_UP_TEST_ENTITY_COUNT_INCREMENT 100000
#define RAMP_UP_TEST_ENTITY_COUNT_MAX 500000

#define DYNAMIC_RAMP_UP_TEST_ENTITY_COUNT_MIN 0
#define DYNAMIC_RAMP_UP_TEST_ENTITY_COUNT_MAX 100000

#endif
